export const mock = {
  additional_info: '',
  auto_return: '',
  back_urls: {
    failure: '',
    pending: '',
    success: '',
  },
  binary_mode: false,
  client_id: '7136722070390133',
  collector_id: 478787616,
  coupon_code: null,
  coupon_labels: null,
  date_created: '2020-05-01T18:15:21.308+00:00',
  expiration_date_from: null,
  expiration_date_to: null,
  expires: false,
  external_reference: '',
  id: '478787616-69da0d4e-a762-4f10-b7eb-574a8b501341',
  init_point: 'https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=478787616-69da0d4e-a762-4f10-b7eb-574a8b501341',
  internal_metadata: null,
  items: [
    {
      id: '',
      category_id: '',
      currency_id: 'ARS',
      description: 'Multicolor Item',
      title: 'Dummy Item',
      quantity: 1,
      unit_price: 10,
    },
  ],
  marketplace: 'NONE',
  marketplace_fee: 0,
  metadata: {},
  notification_url: null,
  operation_type: 'regular_payment',
  payer: {
    phone: {
      area_code: '',
      number: '',
    },
    address: {
      zip_code: '',
      street_name: '',
      street_number: null,
    },
    email: '',
    identification: {
      number: '',
      type: '',
    },
    name: '',
    surname: '',
    date_created: null,
    last_purchase: null,
  },
  payment_methods: {
    default_card_id: null,
    default_payment_method_id: null,
    excluded_payment_methods: [
      {
        id: '',
      },
    ],
    excluded_payment_types: [
      {
        id: '',
      },
    ],
    installments: null,
    default_installments: null,
  },
  processing_modes: null,
  product_id: null,
  redirect_urls: {
    failure: '',
    pending: '',
    success: '',
  },
  sandbox_init_point: 'https://sandbox.mercadopago.com.ar/checkout/v1/redirect?pref_id=478787616-69da0d4e-a762-4f10-b7eb-574a8b501341',
  site_id: 'MLA',
  shipments: {
    default_shipping_method: null,
    receiver_address: {
      zip_code: '',
      street_name: '',
      street_number: null,
      floor: '',
      apartment: '',
      city_name: null,
      state_name: null,
      country_name: null,
    },
  },
  total_amount: null,
  last_updated: null,
};
